
import { Question, QuestionType } from '../types';

export const GRADE_7_BANK: Record<string, Omit<Question, 'id'>[]> = {
  'EF07CI01': [
    { text: "Qual destas é considerada uma máquina simples?", type: QuestionType.MULTIPLE_CHOICE, options: ["Alavanca", "Computador", "Motor de carro", "Televisão"], correctAnswer: 0, explanation: "Máquinas simples, como a alavanca, ajudam a realizar trabalho com menos esforço físico.", bnccCode: "EF07CI01" },
    { text: "O que uma roldana fixa faz?", type: QuestionType.MULTIPLE_CHOICE, options: ["Muda a direção da força aplicada", "Aumenta a força em 10 vezes", "Cria energia elétrica", "Diminui o peso do objeto"], correctAnswer: 0, explanation: "A roldana fixa apenas muda a direção da força, facilitando o ato de puxar.", bnccCode: "EF07CI01" },
    { text: "Uma rampa é um exemplo de qual máquina simples?", type: QuestionType.MULTIPLE_CHOICE, options: ["Plano inclinado", "Parafuso", "Roda e eixo", "Alavanca de 3º grau"], correctAnswer: 0, explanation: "O plano inclinado permite elevar cargas com menos força ao longo de uma distância maior.", bnccCode: "EF07CI01" },
    { text: "Qual destes objetos usa o princípio da alavanca?", type: QuestionType.MULTIPLE_CHOICE, options: ["Tesoura", "Lâmpada", "Pilha", "Vela"], correctAnswer: 0, explanation: "A tesoura funciona como uma alavanca interfixa para cortar materiais.", bnccCode: "EF07CI01" },
    { text: "O que é o 'ponto de apoio' em uma alavanca?", type: QuestionType.MULTIPLE_CHOICE, options: ["O local fixo onde a barra gira", "Onde aplicamos a força", "O peso que queremos levantar", "O final da corda"], correctAnswer: 0, explanation: "O ponto de apoio (fulcro) é onde a alavanca se sustenta para girar.", bnccCode: "EF07CI01" },
    { text: "Um quebra-nozes é uma alavanca do tipo:", type: QuestionType.MULTIPLE_CHOICE, options: ["Inter-resistente", "Interfixa", "Interpotente", "Inativa"], correctAnswer: 0, explanation: "A resistência (noz) fica entre o ponto de apoio e a força aplicada.", bnccCode: "EF07CI01" },
    { text: "Qual a vantagem de usar uma roldana móvel?", type: QuestionType.MULTIPLE_CHOICE, options: ["Reduz a força necessária pela metade", "Aumenta o peso do objeto", "Não muda nada", "Esquenta o objeto"], correctAnswer: 0, explanation: "A roldana móvel divide o peso da carga entre as cordas.", bnccCode: "EF07CI01" },
    { text: "O parafuso pode ser considerado uma variação de qual máquina?", type: QuestionType.MULTIPLE_CHOICE, options: ["Plano inclinado enrolado", "Alavanca curta", "Roda dentada", "Motor elétrico"], correctAnswer: 0, explanation: "O parafuso é um plano inclinado em forma de espiral.", bnccCode: "EF07CI01" },
    { text: "Para levantar uma pedra muito pesada, onde o ponto de apoio deve ficar?", type: QuestionType.MULTIPLE_CHOICE, options: ["Próximo à pedra", "Bem longe da pedra", "Exatamente no meio da barra", "Em cima da pedra"], correctAnswer: 0, explanation: "Quanto mais perto da carga estiver o ponto de apoio, menor a força necessária.", bnccCode: "EF07CI01" },
    { text: "Máquinas simples foram criadas para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Facilitar o trabalho humano", "Substituir a inteligência", "Gastar mais energia", "Destruir a natureza"], correctAnswer: 0, explanation: "Elas multiplicam a força ou mudam sua direção para ajudar nas tarefas.", bnccCode: "EF07CI01" }
  ],
  'EF07CI02': [
    { text: "Qual a definição científica de calor?", type: QuestionType.MULTIPLE_CHOICE, options: ["Energia térmica em movimento", "O mesmo que temperatura", "Algo que só existe no verão", "Um tipo de líquido invisível"], correctAnswer: 0, explanation: "Calor é a transferência de energia do corpo mais quente para o mais frio.", bnccCode: "EF07CI02" },
    { text: "O que a temperatura mede em um corpo?", type: QuestionType.MULTIPLE_CHOICE, options: ["O nível de agitação das moléculas", "A quantidade de água", "O peso total", "A cor do objeto"], correctAnswer: 0, explanation: "Quanto mais agitadas as moléculas, maior a temperatura.", bnccCode: "EF07CI02" },
    { text: "Qual instrumento usamos para medir a temperatura?", type: QuestionType.MULTIPLE_CHOICE, options: ["Termômetro", "Barômetro", "Balança", "Régua"], correctAnswer: 0, explanation: "O termômetro usa a dilatação de materiais para indicar a temperatura.", bnccCode: "EF07CI02" },
    { text: "O calor sempre flui naturalmente de onde para onde?", type: QuestionType.MULTIPLE_CHOICE, options: ["Do corpo quente para o frio", "Do corpo frio para o quente", "De baixo para cima apenas", "Não flui"], correctAnswer: 0, explanation: "É uma lei da termodinâmica: o calor busca o equilíbrio.", bnccCode: "EF07CI02" },
    { text: "A unidade de temperatura mais usada no Brasil é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Celsius (°C)", "Fahrenheit (°F)", "Kelvin (K)", "Metros"], correctAnswer: 0, explanation: "Usamos a escala Celsius, onde a água ferve a 100°C.", bnccCode: "EF07CI02" },
    { text: "O que acontece com a maioria dos materiais quando aquecidos?", type: QuestionType.MULTIPLE_CHOICE, options: ["Eles se dilatam (aumentam)", "Eles diminuem de tamanho", "Eles ficam mais pesados", "Eles mudam de cor apenas"], correctAnswer: 0, explanation: "O calor aumenta a agitação e o espaço entre as partículas.", bnccCode: "EF07CI02" },
    { text: "O zero absoluto (0 Kelvin) representa:", type: QuestionType.MULTIPLE_CHOICE, options: ["A ausência total de agitação molecular", "A temperatura do gelo comum", "O calor do Sol", "O ponto de ebulição"], correctAnswer: 0, explanation: "É o limite teórico onde as partículas param de se mover.", bnccCode: "EF07CI02" },
    { text: "Dois corpos em equilíbrio térmico possuem:", type: QuestionType.MULTIPLE_CHOICE, options: ["A mesma temperatura", "O mesmo tamanho", "Pesos diferentes", "Cores iguais"], correctAnswer: 0, explanation: "Equilíbrio significa que não há mais troca de calor entre eles.", bnccCode: "EF07CI02" },
    { text: "Por que sentimos frio ao tocar no metal?", type: QuestionType.MULTIPLE_CHOICE, options: ["O metal retira calor da nossa mão rápido", "O metal produz gelo", "Nossa mão é mais fria que o metal", "O metal é um isolante"], correctAnswer: 0, explanation: "Metais conduzem calor muito bem, roubando nossa energia térmica.", bnccCode: "EF07CI02" },
    { text: "O suor ajuda o corpo a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Diminuir a temperatura corporal", "Aumentar o calor", "Ficar mais cansado", "Produzir energia"], correctAnswer: 0, explanation: "A evaporação do suor retira calor da pele, resfriando o corpo.", bnccCode: "EF07CI02" }
  ],
  'EF07CI17CA': [
    { text: "Qual reino engloba todas as bactérias?", type: QuestionType.MULTIPLE_CHOICE, options: ["Monera", "Protista", "Fungi", "Plantae"], correctAnswer: 0, explanation: "O Reino Monera é formado por seres procariontes e unicelulares.", bnccCode: "EF07CI17CA" },
    { text: "Os cogumelos e bolores pertencem ao reino:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fungi", "Animalia", "Plantae", "Monera"], correctAnswer: 0, explanation: "Fungos não fazem fotossíntese e decompõem matéria orgânica.", bnccCode: "EF07CI17CA" },
    { text: "Qual a principal característica das plantas?", type: QuestionType.MULTIPLE_CHOICE, options: ["Produzem o próprio alimento (autótrofas)", "Comem outros animais", "Não possuem células", "Podem se locomover"], correctAnswer: 0, explanation: "Plantas realizam fotossíntese para produzir energia.", bnccCode: "EF07CI17CA" },
    { text: "Protozoários e algas pertencem ao reino:", type: QuestionType.MULTIPLE_CHOICE, options: ["Protista", "Fungi", "Animalia", "Monera"], correctAnswer: 0, explanation: "É um reino muito diverso com seres eucariontes simples.", bnccCode: "EF07CI17CA" },
    { text: "O Reino Animalia é composto por seres:", type: QuestionType.MULTIPLE_CHOICE, options: ["Multicelulares e heterótrofos", "Unicelulares e autótrofos", "Que fazem fotossíntese", "Sem DNA"], correctAnswer: 0, explanation: "Animais precisam se alimentar de outros seres vivos.", bnccCode: "EF07CI17CA" },
    { text: "Qual destes reinos possui células Procariontes (sem núcleo definido)?", type: QuestionType.MULTIPLE_CHOICE, options: ["Monera", "Plantae", "Fungi", "Animalia"], correctAnswer: 0, explanation: "Apenas as bactérias e arqueas possuem esse tipo simples de célula.", bnccCode: "EF07CI17CA" },
    { text: "As leveduras (usadas no pão) são seres do reino:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fungi", "Monera", "Protista", "Plantae"], correctAnswer: 0, explanation: "Leveduras são fungos unicelulares importantes na culinária.", bnccCode: "EF07CI17CA" },
    { text: "Qual reino é responsável pela maior produção de oxigênio do planeta (via algas)?", type: QuestionType.MULTIPLE_CHOICE, options: ["Protista", "Animalia", "Fungi", "Monera"], correctAnswer: 0, explanation: "As algas marinhas (Protistas) são o pulmão do mundo.", bnccCode: "EF07CI17CA" },
    { text: "Vertebrados e invertebrados são divisões do reino:", type: QuestionType.MULTIPLE_CHOICE, options: ["Animalia", "Plantae", "Protista", "Monera"], correctAnswer: 0, explanation: "Incluem desde insetos até seres humanos.", bnccCode: "EF07CI17CA" },
    { text: "Os vírus pertencem a qual destes cinco reinos?", type: QuestionType.MULTIPLE_CHOICE, options: ["Nenhum (não são considerados células)", "Monera", "Protista", "Fungi"], correctAnswer: 0, explanation: "Vírus são acelulares e não se encaixam na classificação clássica de reinos.", bnccCode: "EF07CI17CA" }
  ]
  // Adicionar aqui os demais bancos (EF07CI03 a EF07CI16) seguindo a mesma estrutura...
};
