
import { Question, QuestionType } from '../types';

export const GRADE_6_BANK: Record<string, Omit<Question, 'id'>[]> = {
  'EF06CI01': [
    { text: "O que caracteriza uma mistura homogênea?", type: QuestionType.MULTIPLE_CHOICE, options: ["Apresenta apenas uma fase", "Apresenta duas ou mais fases", "Os componentes são visíveis a olho nu", "É composta por apenas um elemento"], correctAnswer: 0, explanation: "Misturas homogêneas são aquelas em que não conseguimos distinguir os componentes.", bnccCode: "EF06CI01" },
    { text: "Qual destes é um exemplo de mistura homogênea?", type: QuestionType.MULTIPLE_CHOICE, options: ["Água e sal dissolvido", "Água e areia", "Salada de frutas", "Água e óleo"], correctAnswer: 0, explanation: "Quando o sal dissolve na água, forma-se uma única fase visível.", bnccCode: "EF06CI01" },
    { text: "O ar atmosférico (limpo) é considerado:", type: QuestionType.MULTIPLE_CHOICE, options: ["Uma mistura homogênea", "Uma substância pura", "Uma mistura heterogênea", "Um elemento químico"], correctAnswer: 0, explanation: "O ar é uma mistura de vários gases que não conseguimos distinguir.", bnccCode: "EF06CI01" },
    { text: "Uma mistura que apresenta duas fases é chamada de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Heterogênea", "Homogênea", "Solução", "Pura"], correctAnswer: 0, explanation: "Misturas com duas ou mais fases são heterogêneas.", bnccCode: "EF06CI01" },
    { text: "O que vemos em uma mistura de água e óleo?", type: QuestionType.MULTIPLE_CHOICE, options: ["Duas fases distintas", "Uma única fase", "O óleo desaparecendo", "A água mudando de cor"], correctAnswer: 0, explanation: "Água e óleo não se misturam, formando uma mistura heterogênea.", bnccCode: "EF06CI01" },
    { text: "O sangue, observado ao microscópio, revela-se como:", type: QuestionType.MULTIPLE_CHOICE, options: ["Uma mistura heterogênea", "Uma mistura homogênea", "Uma substância pura", "Um gás"], correctAnswer: 0, explanation: "Embora pareça homogêneo a olho nu, o microscópio mostra as células e o plasma separadamente.", bnccCode: "EF06CI01" },
    { text: "O granito é um exemplo de mistura:", type: QuestionType.MULTIPLE_CHOICE, options: ["Heterogênea", "Homogênea", "Líquida", "Gasosa"], correctAnswer: 0, explanation: "No granito podemos ver claramente os diferentes minerais (quartzo, feldspato e mica).", bnccCode: "EF06CI01" },
    { text: "Quantas fases tem uma mistura de água, gelo e areia?", type: QuestionType.MULTIPLE_CHOICE, options: ["3 fases", "2 fases", "1 fase", "4 fases"], correctAnswer: 0, explanation: "Cada estado físico ou material diferente conta como uma fase separada.", bnccCode: "EF06CI01" },
    { text: "O soro caseiro é uma mistura:", type: QuestionType.MULTIPLE_CHOICE, options: ["Homogênea", "Heterogênea", "Sólida", "Tóxica"], correctAnswer: 0, explanation: "Água, sal e açúcar dissolvidos formam uma solução homogênea.", bnccCode: "EF06CI01" },
    { text: "O que é um componente em uma mistura?", type: QuestionType.MULTIPLE_CHOICE, options: ["Cada substância que forma a mistura", "O resultado final da mistura", "Apenas a parte líquida", "Apenas a parte sólida"], correctAnswer: 0, explanation: "Componentes são as diferentes substâncias que adicionamos para criar a mistura.", bnccCode: "EF06CI01" }
  ],
  'EF06CI02': [
    { text: "Qual destas é uma evidência de reação química?", type: QuestionType.MULTIPLE_CHOICE, options: ["Mudança de cor", "Apenas mudar de lugar", "Quebrar em pedaços pequenos", "Derreter"], correctAnswer: 0, explanation: "Mudança de cor muitas vezes indica a formação de novas substâncias.", bnccCode: "EF06CI02" },
    { text: "O que acontece em uma transformação química?", type: QuestionType.MULTIPLE_CHOICE, options: ["Surgem novas substâncias", "A matéria continua a mesma", "Ocorre apenas mudança de estado", "O objeto apenas muda de forma"], correctAnswer: 0, explanation: "Diferente da física, a química altera a natureza da matéria.", bnccCode: "EF06CI02" },
    { text: "Qual destes exemplos é uma transformação química?", type: QuestionType.MULTIPLE_CHOICE, options: ["Papel queimando", "Papel rasgado", "Gelo derretendo", "Copo quebrado"], correctAnswer: 0, explanation: "A combustão transforma o papel em cinzas e gases.", bnccCode: "EF06CI02" },
    { text: "A ferrugem em um prego é exemplo de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Transformação química", "Transformação física", "Mistura homogênea", "Evaporação"], correctAnswer: 0, explanation: "O ferro reage com oxigênio e água formando uma nova substância.", bnccCode: "EF06CI02" },
    { text: "O cozimento de um ovo é uma transformação:", type: QuestionType.MULTIPLE_CHOICE, options: ["Química", "Física", "Reversível", "Instantânea"], correctAnswer: 0, explanation: "O calor altera as proteínas do ovo permanentemente.", bnccCode: "EF06CI02" },
    { text: "Qual sinal indica liberação de gás em uma reação?", type: QuestionType.MULTIPLE_CHOICE, options: ["Efervescência (bolhas)", "Resfriamento", "Congelamento", "Escurecimento"], correctAnswer: 0, explanation: "Bolhas indicam que um gás está sendo produzido na reação.", bnccCode: "EF06CI02" },
    { text: "Amadurecimento de uma fruta é uma transformação:", type: QuestionType.MULTIPLE_CHOICE, options: ["Química", "Física", "Mecânica", "Nula"], correctAnswer: 0, explanation: "Ocorre produção de açúcares e mudança de cor e textura por reações internas.", bnccCode: "EF06CI02" },
    { text: "A fotossíntese nas plantas é um processo:", type: QuestionType.MULTIPLE_CHOICE, options: ["Químico", "Físico", "Apenas visual", "De mistura"], correctAnswer: 0, explanation: "Plantas transformam luz, água e CO2 em alimento através de reações complexas.", bnccCode: "EF06CI02" },
    { text: "A queima de uma vela produz:", type: QuestionType.MULTIPLE_CHOICE, options: ["Luz e calor (reação química)", "Apenas luz", "Apenas gelo", "Nada"], correctAnswer: 0, explanation: "A combustão da parafina libera energia e gases.", bnccCode: "EF06CI02" },
    { text: "Transformações que podem voltar ao original são geralmente:", type: QuestionType.MULTIPLE_CHOICE, options: ["Físicas", "Químicas", "Explosivas", "Impossíveis"], correctAnswer: 0, explanation: "Como o gelo que derrete e pode congelar de novo.", bnccCode: "EF06CI02" }
  ],
  'EF06CI03': [
    { text: "Qual método separa areia de água?", type: QuestionType.MULTIPLE_CHOICE, options: ["Filtração", "Destilação", "Catação", "Ventilação"], correctAnswer: 0, explanation: "O filtro retém o sólido (areia) e deixa passar o líquido.", bnccCode: "EF06CI03" },
    { text: "A 'catação' é usada para separar:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sólidos com as mãos/pinças", "Líquidos misturados", "Gases", "Sal da água"], correctAnswer: 0, explanation: "Como escolher feijão antes de cozinhar.", bnccCode: "EF06CI03" },
    { text: "Como se separa o sal da água em uma salina?", type: QuestionType.MULTIPLE_CHOICE, options: ["Evaporação", "Peneiração", "Filtração", "Ímã"], correctAnswer: 0, explanation: "A água evapora com o sol e o sal permanece.", bnccCode: "EF06CI03" },
    { text: "Para separar limalha de ferro de areia, usamos:", type: QuestionType.MULTIPLE_CHOICE, options: ["Separação magnética (ímã)", "Peneiração", "Ventilação", "Água"], correctAnswer: 0, explanation: "O ferro é atraído pelo ímã, a areia não.", bnccCode: "EF06CI03" },
    { text: "O método que usa o vento para separar cascas de grãos é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ventilação", "Levigação", "Decantação", "Sifonação"], correctAnswer: 0, explanation: "O vento leva as partes mais leves (cascas).", bnccCode: "EF06CI03" },
    { text: "A decantação serve para separar misturas onde:", type: QuestionType.MULTIPLE_CHOICE, options: ["O mais denso 'afunda'", "O mais leve 'afunda'", "Tudo se dissolve", "Nada acontece"], correctAnswer: 0, explanation: "Deixa-se a mistura em repouso até o sólido assentar no fundo.", bnccCode: "EF06CI03" },
    { text: "A peneiração separa sólidos por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Tamanho dos grãos", "Cor dos grãos", "Peso dos grãos", "Cheiro"], correctAnswer: 0, explanation: "A malha da peneira deixa passar apenas os menores.", bnccCode: "EF06CI03" },
    { text: "Qual método é usado para fazer café?", type: QuestionType.MULTIPLE_CHOICE, options: ["Filtração", "Catação", "Evaporação", "Imantação"], correctAnswer: 0, explanation: "O filtro de papel retém o pó de café.", bnccCode: "EF06CI03" },
    { text: "Como separar água e óleo?", type: QuestionType.MULTIPLE_CHOICE, options: ["Decantação (funil)", "Filtração", "Peneira", "Catação"], correctAnswer: 0, explanation: "Como não se misturam, o mais denso fica embaixo e pode ser escorrido.", bnccCode: "EF06CI03" },
    { text: "A destilação é usada para separar:", type: QuestionType.MULTIPLE_CHOICE, options: ["Líquidos com pontos de ebulição diferentes", "Pedras e areia", "Papel e plástico", "Ar e poeira"], correctAnswer: 0, explanation: "Aquece-se a mistura até um dos líquidos virar vapor e ser coletado.", bnccCode: "EF06CI03" }
  ],
  'EF06CI04': [
    { text: "O que é um material sintético?", type: QuestionType.MULTIPLE_CHOICE, options: ["Criado pelo homem em laboratório", "Retirado diretamente da natureza", "Uma planta", "Uma rocha"], correctAnswer: 0, explanation: "Materiais sintéticos não existem prontos na natureza.", bnccCode: "EF06CI04" },
    { text: "Qual destes é um exemplo de material sintético?", type: QuestionType.MULTIPLE_CHOICE, options: ["Plástico", "Madeira", "Algodão", "Ouro"], correctAnswer: 0, explanation: "O plástico é produzido artificialmente a partir do petróleo.", bnccCode: "EF06CI04" },
    { text: "O náilon usado em roupas é um material:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sintético", "Natural", "Mineral", "Animal"], correctAnswer: 0, explanation: "É uma fibra artificial criada quimicamente.", bnccCode: "EF06CI04" },
    { text: "Os medicamentos sintéticos servem para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Tratar doenças de forma controlada", "Enfeitar a casa", "Alimentar animais", "Substituir a água"], correctAnswer: 0, explanation: "São desenvolvidos para ter efeitos específicos no organismo.", bnccCode: "EF06CI04" },
    { text: "Um benefício dos materiais sintéticos é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Poderem ser criados com propriedades específicas", "Sempre serem biodegradáveis", "Não poluírem", "Serem gratuitos"], correctAnswer: 0, explanation: "Podemos criar plásticos resistentes, tecidos leves, etc.", bnccCode: "EF06CI04" },
    { text: "Muitos plásticos são feitos a partir de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Petróleo", "Areia", "Leite", "Folhas"], correctAnswer: 0, explanation: "O petróleo é a matéria-prima básica da maioria dos plásticos.", bnccCode: "EF06CI04" },
    { text: "Um problema ambiental dos sintéticos (como o plástico) é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Demoram muito para se decompor", "Desaparecem rápido demais", "São comidos por plantas", "Virar adubo"], correctAnswer: 0, explanation: "A durabilidade extrema causa acúmulo de lixo nos oceanos e solos.", bnccCode: "EF06CI04" },
    { text: "O vidro é considerado:", type: QuestionType.MULTIPLE_CHOICE, options: ["Transformado pelo homem (manufaturado)", "Uma planta", "Um gás", "Um animal"], correctAnswer: 0, explanation: "Embora venha da areia (natural), passa por processo industrial humano.", bnccCode: "EF06CI04" },
    { text: "A borracha sintética substitui qual material natural?", type: QuestionType.MULTIPLE_CHOICE, options: ["Látex da seringueira", "Tronco de árvore", "Pedra", "Água"], correctAnswer: 0, explanation: "Criada para suprir a alta demanda de pneus e indústrias.", bnccCode: "EF06CI04" },
    { text: "Materiais biodegradáveis são aqueles que:", type: QuestionType.MULTIPLE_CHOICE, options: ["A natureza decompõe facilmente", "Duram para sempre", "São feitos de ferro", "Brilham no escuro"], correctAnswer: 0, explanation: "São mais amigáveis ao meio ambiente pois se desintegram naturalmente.", bnccCode: "EF06CI04" }
  ],
  'EF06CI05': [
    { text: "Quem observou as primeiras 'células' em cortiça?", type: QuestionType.MULTIPLE_CHOICE, options: ["Robert Hooke", "Isaac Newton", "Charles Darwin", "Albert Einstein"], correctAnswer: 0, explanation: "Em 1665, ele usou um microscópio simples para ver pequenos espaços na cortiça.", bnccCode: "EF06CI05" },
    { text: "Segundo a Teoria Celular, todos os seres vivos são:", type: QuestionType.MULTIPLE_CHOICE, options: ["Formados por células", "Feitos de água", "Capazes de voar", "Imortais"], correctAnswer: 0, explanation: "A célula é a unidade básica da vida.", bnccCode: "EF06CI05" },
    { text: "Qual destas é a parte que envolve e protege a célula?", type: QuestionType.MULTIPLE_CHOICE, options: ["Membrana Plasmática", "Núcleo", "Citoplasma", "DNA"], correctAnswer: 0, explanation: "Ela controla o que entra e sai da célula.", bnccCode: "EF06CI05" },
    { text: "Onde fica o material genético (DNA) na maioria das células?", type: QuestionType.MULTIPLE_CHOICE, options: ["No Núcleo", "Na membrana", "No citoplasma", "Fora da célula"], correctAnswer: 0, explanation: "O núcleo é o centro de comando da célula.", bnccCode: "EF06CI05" },
    { text: "Como se chama a parte gelatinosa dentro da célula?", type: QuestionType.MULTIPLE_CHOICE, options: ["Citoplasma", "Membrana", "Parede", "Sangue"], correctAnswer: 0, explanation: "É onde ficam mergulhadas as organelas celulares.", bnccCode: "EF06CI05" },
    { text: "Seres formados por uma única célula são chamados:", type: QuestionType.MULTIPLE_CHOICE, options: ["Unicelulares", "Pluricelulares", "Bicelulares", "Gigantes"], correctAnswer: 0, explanation: "Exemplos: bactérias e alguns protozoários.", bnccCode: "EF06CI05" },
    { text: "Nós, seres humanos, somos seres:", type: QuestionType.MULTIPLE_CHOICE, options: ["Pluricelulares", "Unicelulares", "Acelulares", "Minerais"], correctAnswer: 0, explanation: "Somos formados por trilhões de células.", bnccCode: "EF06CI05" },
    { text: "A unidade básica da vida é:", type: QuestionType.MULTIPLE_CHOICE, options: ["A célula", "O átomo", "O órgão", "O sistema"], correctAnswer: 0, explanation: "Tudo o que é vivo possui pelo menos uma célula.", bnccCode: "EF06CI05" },
    { text: "As organelas servem para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Realizar funções específicas (respirar, nutrir)", "Enfeitar a célula", "Proteger contra o sol", "Nada"], correctAnswer: 0, explanation: "São como 'pequenos órgãos' da célula.", bnccCode: "EF06CI05" },
    { text: "Células procariontes são aquelas que:", type: QuestionType.MULTIPLE_CHOICE, options: ["Não possuem núcleo organizado", "Possuem núcleo definido", "São muito grandes", "Não existem"], correctAnswer: 0, explanation: "O DNA fica solto no citoplasma (ex: bactérias).", bnccCode: "EF06CI05" }
  ],
  'EF06CI06': [
    { text: "Qual a sequência correta da organização biológica?", type: QuestionType.MULTIPLE_CHOICE, options: ["Célula -> Tecido -> Órgão -> Sistema", "Órgão -> Célula -> Tecido -> Sistema", "Tecido -> Órgão -> Sistema -> Célula", "Sistema -> Órgão -> Tecido -> Célula"], correctAnswer: 0, explanation: "O menor forma o maior em níveis crescentes.", bnccCode: "EF06CI06" },
    { text: "Um conjunto de células semelhantes que realizam a mesma função forma:", type: QuestionType.MULTIPLE_CHOICE, options: ["Um Tecido", "Um Órgão", "Um Sistema", "Um Organismo"], correctAnswer: 0, explanation: "Exemplo: tecido muscular.", bnccCode: "EF06CI06" },
    { text: "O coração é um exemplo de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Órgão", "Célula", "Tecido", "Sistema"], correctAnswer: 0, explanation: "Um órgão é formado por diferentes tecidos trabalhando juntos.", bnccCode: "EF06CI06" },
    { text: "O conjunto de órgãos que trabalham juntos (como estômago, boca, intestinos) forma:", type: QuestionType.MULTIPLE_CHOICE, options: ["Um Sistema", "Um Tecido", "Uma Célula", "Um Átomo"], correctAnswer: 0, explanation: "Neste caso, o Sistema Digestório.", bnccCode: "EF06CI06" },
    { text: "O nível mais alto de organização de um ser vivo completo é:", type: QuestionType.MULTIPLE_CHOICE, options: ["O Organismo", "A Célula", "O Órgão", "A Molécula"], correctAnswer: 0, explanation: "É o indivíduo como um todo.", bnccCode: "EF06CI06" },
    { text: "Os ossos do nosso corpo formam qual nível?", type: QuestionType.MULTIPLE_CHOICE, options: ["Órgãos que compõem um Sistema", "Apenas tecidos", "Células soltas", "Nada"], correctAnswer: 0, explanation: "Cada osso é um órgão do Sistema Esquelético.", bnccCode: "EF06CI06" },
    { text: "A pele é considerada o maior _______ do corpo humano:", type: QuestionType.MULTIPLE_CHOICE, options: ["Órgão", "Tecido", "Sistema", "Célula"], correctAnswer: 0, explanation: "Ela é composta por vários tecidos (epitelial, conjuntivo, etc).", bnccCode: "EF06CI06" },
    { text: "Qual o nível de organização de uma bactéria?", type: QuestionType.MULTIPLE_CHOICE, options: ["Célula/Organismo", "Sistema", "Tecido", "Órgão"], correctAnswer: 0, explanation: "Por ser unicelular, a célula já é o organismo completo.", bnccCode: "EF06CI06" },
    { text: "Vários sistemas juntos formam o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Corpo Humano (Organismo)", "Tecido", "DNA", "Clã"], correctAnswer: 0, explanation: "A união de todos os sistemas forma o ser vivo.", bnccCode: "EF06CI06" },
    { text: "O sangue é tecnicamente classificado como:", type: QuestionType.MULTIPLE_CHOICE, options: ["Um tecido líquido", "Um sistema", "Uma célula gigante", "Um órgão"], correctAnswer: 0, explanation: "É o tecido conjuntivo sanguíneo.", bnccCode: "EF06CI06" }
  ],
  'EF06CI07': [
    { text: "Qual a função principal do sistema nervoso?", type: QuestionType.MULTIPLE_CHOICE, options: ["Coordenar as ações do corpo", "Digerir alimentos", "Bombear sangue", "Produzir ossos"], correctAnswer: 0, explanation: "Ele recebe informações e envia comandos para o corpo.", bnccCode: "EF06CI07" },
    { text: "Como se chama a célula principal do sistema nervoso?", type: QuestionType.MULTIPLE_CHOICE, options: ["Neurônio", "Hemácia", "Fibra muscular", "Pele"], correctAnswer: 0, explanation: "Neurônios transmitem impulsos elétricos.", bnccCode: "EF06CI07" },
    { text: "O Sistema Nervoso Central é formado por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Encéfalo e Medula Espinal", "Coração e Pulmão", "Braços e Pernas", "Estômago"], correctAnswer: 0, explanation: "São os centros de processamento de informação.", bnccCode: "EF06CI07" },
    { text: "O cérebro fica localizado dentro do:", type: QuestionType.MULTIPLE_CHOICE, options: ["Encéfalo (Crânio)", "Pescoço", "Tórax", "Barriga"], correctAnswer: 0, explanation: "O crânio protege o cérebro contra impactos.", bnccCode: "EF06CI07" },
    { text: "A medula espinal passa por dentro de qual estrutura?", type: QuestionType.MULTIPLE_CHOICE, options: ["Coluna vertebral", "Fêmur", "Costelas", "Crânio"], correctAnswer: 0, explanation: "As vértebras protegem a medula.", bnccCode: "EF06CI07" },
    { text: "O que são os nervos?", type: QuestionType.MULTIPLE_CHOICE, options: ["'Fios' que levam mensagens pelo corpo", "Ossos finos", "Músculos esticados", "Veias"], correctAnswer: 0, explanation: "Eles conectam o sistema central ao resto do corpo.", bnccCode: "EF06CI07" },
    { text: "Ações voluntárias são aquelas que:", type: QuestionType.MULTIPLE_CHOICE, options: ["Nós controlamos (como andar)", "Acontecem sozinhas (como batimento cardíaco)", "Não existem", "Só acontecem dormindo"], correctAnswer: 0, explanation: "O cérebro decide quando realizar essas ações.", bnccCode: "EF06CI07" },
    { text: "O ato de tirar a mão rápido de algo quente é um:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ato reflexo", "Pensamento profundo", "Hábito", "Erro"], correctAnswer: 0, explanation: "É uma resposta rápida e automática da medula para proteção.", bnccCode: "EF06CI07" },
    { text: "Qual parte do encéfalo coordena o equilíbrio e os movimentos?", type: QuestionType.MULTIPLE_CHOICE, options: ["Cerebelo", "Cérebro", "Tronco encefálico", "Medula"], correctAnswer: 0, explanation: "Ele é essencial para andar e manter a postura.", bnccCode: "EF06CI07" },
    { text: "A comunicação entre neurônios é chamada de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sinapse", "Eletricidade", "Conversa", "Ponte"], correctAnswer: 0, explanation: "É o espaço onde neurotransmissores passam a informação.", bnccCode: "EF06CI07" }
  ],
  'EF06CI08': [
    { text: "Qual órgão é responsável pela visão?", type: QuestionType.MULTIPLE_CHOICE, options: ["Olho", "Ouvido", "Nariz", "Língua"], correctAnswer: 0, explanation: "Os olhos captam a luz do ambiente.", bnccCode: "EF06CI08" },
    { text: "A parte colorida do olho chama-se:", type: QuestionType.MULTIPLE_CHOICE, options: ["Íris", "Pupila", "Retina", "Cristalino"], correctAnswer: 0, explanation: "A íris controla a abertura da pupila.", bnccCode: "EF06CI08" },
    { text: "O 'buraquinho' preto no centro do olho é a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Pupila", "Lente", "Esclera", "Córnea"], correctAnswer: 0, explanation: "É por onde a luz entra no olho.", bnccCode: "EF06CI08" },
    { text: "Onde a imagem é formada dentro do olho?", type: QuestionType.MULTIPLE_CHOICE, options: ["Na Retina", "Na Íris", "Na Córnea", "Nas pálpebras"], correctAnswer: 0, explanation: "A retina funciona como o 'filme' de uma câmera.", bnccCode: "EF06CI08" },
    { text: "A lente natural do olho que foca a imagem é o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Cristalino", "Nervo óptico", "Pupila", "Vidro"], correctAnswer: 0, explanation: "Ele muda de forma para focar objetos perto ou longe.", bnccCode: "EF06CI08" },
    { text: "Como a imagem chega ao cérebro?", type: QuestionType.MULTIPLE_CHOICE, options: ["Pelo Nervo Óptico", "Pelo sangue", "Pelo ar", "Não chega"], correctAnswer: 0, explanation: "O nervo leva os sinais elétricos da retina para o cérebro.", bnccCode: "EF06CI08" },
    { text: "A dificuldade de enxergar de longe chama-se:", type: QuestionType.MULTIPLE_CHOICE, options: ["Miopia", "Hipermetropia", "Astigmatismo", "Cegueira"], correctAnswer: 0, explanation: "Míopes precisam de óculos para ver objetos distantes.", bnccCode: "EF06CI08" },
    { text: "O que a pupila faz em ambientes muito claros?", type: QuestionType.MULTIPLE_CHOICE, options: ["Diminui (contrai)", "Aumenta (dilata)", "Muda de cor", "Fecha totalmente"], correctAnswer: 0, explanation: "Ela diminui para não deixar entrar luz excessiva.", bnccCode: "EF06CI08" },
    { text: "As lágrimas servem para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Lubrificar e proteger o olho", "Enxergar melhor à noite", "Mudar a cor da íris", "Nada"], correctAnswer: 0, explanation: "Elas limpam e mantêm a superfície do olho úmida.", bnccCode: "EF06CI08" },
    { text: "Para corrigir a visão, usamos lentes em:", type: QuestionType.MULTIPLE_CHOICE, options: ["Óculos ou lentes de contato", "Espelhos", "Binóculos", "Telescópios"], correctAnswer: 0, explanation: "As lentes ajustam o foco da luz para a retina.", bnccCode: "EF06CI08" }
  ],
  'EF06CI09': [
    { text: "Qual a função do sistema esquelético?", type: QuestionType.MULTIPLE_CHOICE, options: ["Sustentação e proteção", "Produção de gordura", "Digestão", "Respiração"], correctAnswer: 0, explanation: "Os ossos dão forma ao corpo e protegem órgãos vitais.", bnccCode: "EF06CI09" },
    { text: "Quantos ossos tem, aproximadamente, um adulto?", type: QuestionType.MULTIPLE_CHOICE, options: ["206", "100", "500", "50"], correctAnswer: 0, explanation: "O esqueleto humano é complexo e resistente.", bnccCode: "EF06CI09" },
    { text: "O que permite o movimento dos ossos?", type: QuestionType.MULTIPLE_CHOICE, options: ["Músculos e articulações", "Apenas a pele", "O vento", "O sangue"], correctAnswer: 0, explanation: "Músculos puxam os ossos através das articulações.", bnccCode: "EF06CI09" },
    { text: "As articulações são:", type: QuestionType.MULTIPLE_CHOICE, options: ["Encontro de dois ou mais ossos", "Tipos de ossos curtos", "Músculos do braço", "Células do sangue"], correctAnswer: 0, explanation: "Exemplos: joelho, cotovelo, ombro.", bnccCode: "EF06CI09" },
    { text: "Os músculos que controlamos voluntariamente são:", type: QuestionType.MULTIPLE_CHOICE, options: ["Músculos esqueléticos", "Músculo do coração", "Músculos do estômago", "Nenhum"], correctAnswer: 0, explanation: "São os que usamos para andar, correr e abraçar.", bnccCode: "EF06CI09" },
    { text: "O batimento do coração é feito por qual músculo?", type: QuestionType.MULTIPLE_CHOICE, options: ["Músculo cardíaco (involuntário)", "Músculo do braço", "Osso", "Nervo"], correctAnswer: 0, explanation: "Ele trabalha sem que precisemos pensar.", bnccCode: "EF06CI09" },
    { text: "Qual mineral é fundamental para ossos fortes?", type: QuestionType.MULTIPLE_CHOICE, options: ["Cálcio", "Ferro", "Ouro", "Açúcar"], correctAnswer: 0, explanation: "O cálcio dá rigidez ao tecido ósseo.", bnccCode: "EF06CI09" },
    { text: "O crânio protege qual órgão?", type: QuestionType.MULTIPLE_CHOICE, options: ["Cérebro", "Coração", "Pulmão", "Estômago"], correctAnswer: 0, explanation: "É um conjunto de ossos muito resistentes.", bnccCode: "EF06CI09" },
    { text: "O que liga o músculo ao osso?", type: QuestionType.MULTIPLE_CHOICE, options: ["Tendão", "Articulação", "Pele", "Nervo"], correctAnswer: 0, explanation: "Tendões são cordões resistentes que transmitem a força muscular.", bnccCode: "EF06CI09" },
    { text: "Qual o maior osso do corpo humano?", type: QuestionType.MULTIPLE_CHOICE, options: ["Fêmur (na coxa)", "Rádio", "Costela", "Crânio"], correctAnswer: 0, explanation: "O fêmur suporta grande parte do peso do corpo.", bnccCode: "EF06CI09" }
  ],
  'EF06CI10': [
    { text: "O que são drogas?", type: QuestionType.MULTIPLE_CHOICE, options: ["Substâncias que alteram o funcionamento do corpo", "Apenas remédios proibidos", "Qualquer tipo de comida", "Apenas líquidos"], correctAnswer: 0, explanation: "Podem ser naturais ou sintéticas e afetam o sistema nervoso.", bnccCode: "EF06CI10" },
    { text: "Drogas lícitas são aquelas que:", type: QuestionType.MULTIPLE_CHOICE, options: ["Têm venda permitida por lei", "São proibidas para todos", "Não fazem mal nenhum", "São feitas de plantas"], correctAnswer: 0, explanation: "Exemplos: álcool, cigarro e medicamentos.", bnccCode: "EF06CI10" },
    { text: "Drogas ilícitas são aquelas que:", type: QuestionType.MULTIPLE_CHOICE, options: ["Têm venda proibida por lei", "Podem ser compradas no mercado", "São apenas remédios", "Não existem"], correctAnswer: 0, explanation: "Sua produção e venda são crimes.", bnccCode: "EF06CI10" },
    { text: "O cigarro afeta principalmente qual sistema?", type: QuestionType.MULTIPLE_CHOICE, options: ["Respiratório", "Digestório", "Esquelético", "Auditivo"], correctAnswer: 0, explanation: "Causa danos graves aos pulmões e vias aéreas.", bnccCode: "EF06CI10" },
    { text: "O álcool afeta principalmente qual capacidade?", type: QuestionType.MULTIPLE_CHOICE, options: ["Coordenação e reflexos", "Crescimento de altura", "Cor dos olhos", "Audição"], correctAnswer: 0, explanation: "Ele atua como depressor do sistema nervoso central.", bnccCode: "EF06CI10" },
    { text: "O uso indevido de medicamentos pode causar:", type: QuestionType.MULTIPLE_CHOICE, options: ["Intoxicação e dependência", "Cura imediata de tudo", "Fome", "Sono eterno"], correctAnswer: 0, explanation: "Remédios só devem ser usados com orientação médica.", bnccCode: "EF06CI10" },
    { text: "Dependência química é quando:", type: QuestionType.MULTIPLE_CHOICE, options: ["O corpo precisa da droga para funcionar", "A pessoa usa apenas uma vez", "A pessoa para de usar quando quer", "Não existe"], correctAnswer: 0, explanation: "É uma doença crônica que afeta o comportamento.", bnccCode: "EF06CI10" },
    { text: "Drogas estimulantes fazem o cérebro:", type: QuestionType.MULTIPLE_CHOICE, options: ["Trabalhar mais rápido (acelerar)", "Ficar mais lento", "Dormir", "Esquecer tudo"], correctAnswer: 0, explanation: "Exemplo: cafeína e algumas drogas ilícitas.", bnccCode: "EF06CI10" },
    { text: "Drogas depressoras fazem o cérebro:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ficar mais lento", "Ficar mais rápido", "Brilhar", "Voar"], correctAnswer: 0, explanation: "Diminuem a atividade do sistema nervoso.", bnccCode: "EF06CI10" },
    { text: "A melhor forma de prevenir problemas com drogas é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Informação e escolhas saudáveis", "Experimentar para saber", "Ignorar o assunto", "Usar apenas lícitas"], correctAnswer: 0, explanation: "Saber os riscos ajuda a dizer não.", bnccCode: "EF06CI10" }
  ],
  'EF06CI11': [
    { text: "Qual a camada mais superficial da Terra?", type: QuestionType.MULTIPLE_CHOICE, options: ["Crosta Terrestre", "Manto", "Núcleo Externo", "Núcleo Interno"], correctAnswer: 0, explanation: "É a camada onde vivemos e onde estão os oceanos.", bnccCode: "EF06CI11" },
    { text: "A camada intermediária da Terra, feita de magma, é o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Manto", "Crosta", "Núcleo", "Ar"], correctAnswer: 0, explanation: "Fica entre a crosta e o núcleo.", bnccCode: "EF06CI11" },
    { text: "A camada mais quente e profunda da Terra é o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Núcleo", "Manto", "Crosta", "Litosfera"], correctAnswer: 0, explanation: "Pode chegar a temperaturas de 6000°C.", bnccCode: "EF06CI11" },
    { text: "Do que é feito principalmente o núcleo da Terra?", type: QuestionType.MULTIPLE_CHOICE, options: ["Ferro e Níquel", "Água e Sal", "Plástico e Vidro", "Ar"], correctAnswer: 0, explanation: "Metais pesados que dão o magnetismo ao planeta.", bnccCode: "EF06CI11" },
    { text: "O que é o magma?", type: QuestionType.MULTIPLE_CHOICE, options: ["Rocha derretida pelo calor", "Água fervente", "Ar quente", "Gelo"], correctAnswer: 0, explanation: "Encontra-se no manto e sai pelos vulcões como lava.", bnccCode: "EF06CI11" },
    { text: "A parte sólida externa (Crosta + Manto superior) chama-se:", type: QuestionType.MULTIPLE_CHOICE, options: ["Litosfera", "Atmosfera", "Hidrosfera", "Biosfera"], correctAnswer: 0, explanation: "Litos vem do grego 'pedra'.", bnccCode: "EF06CI11" },
    { text: "Como sabemos sobre o interior da Terra?", type: QuestionType.MULTIPLE_CHOICE, options: ["Por terremotos e vulcões", "Fomos lá pessoalmente", "Por satélites", "Não sabemos"], correctAnswer: 0, explanation: "Ondas sísmicas ajudam a mapear as camadas.", bnccCode: "EF06CI11" },
    { text: "As placas tectônicas ficam sobre qual camada?", type: QuestionType.MULTIPLE_CHOICE, options: ["Litosfera (sobre o manto)", "Núcleo", "Ar", "Espaço"], correctAnswer: 0, explanation: "Elas 'flutuam' e se movem lentamente.", bnccCode: "EF06CI11" },
    { text: "O núcleo interno da Terra é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sólido (devido à pressão)", "Líquido", "Gasoso", "Frio"], correctAnswer: 0, explanation: "A pressão é tão alta que o metal não consegue derreter.", bnccCode: "EF06CI11" },
    { text: "O núcleo externo da Terra é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Líquido", "Sólido", "Gelo", "Vácuo"], correctAnswer: 0, explanation: "Seu movimento gera o campo magnético da Terra.", bnccCode: "EF06CI11" }
  ],
  'EF06CI12': [
    { text: "Rocha formada pelo resfriamento do magma é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Magmática (ou Ígnea)", "Sedimentar", "Metamórfica", "Areia"], correctAnswer: 0, explanation: "Vem diretamente do magma ou lava resfriada.", bnccCode: "EF06CI12" },
    { text: "Rocha formada pelo acúmulo de detritos (restos) é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sedimentar", "Magmática", "Metamórfica", "Preciosa"], correctAnswer: 0, explanation: "Formada por camadas que se compactam com o tempo.", bnccCode: "EF06CI12" },
    { text: "Rocha que se transforma por pressão e calor é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Metamórfica", "Sedimentar", "Ígnea", "Fóssil"], correctAnswer: 0, explanation: "Meta vem de mudança, morfo de forma.", bnccCode: "EF06CI12" },
    { text: "O granito é um exemplo de rocha:", type: QuestionType.MULTIPLE_CHOICE, options: ["Magmática", "Sedimentar", "Metamórfica", "Mole"], correctAnswer: 0, explanation: "Formado pelo resfriamento lento do magma dentro da Terra.", bnccCode: "EF06CI12" },
    { text: "Onde geralmente encontramos fósseis?", type: QuestionType.MULTIPLE_CHOICE, options: ["Rochas Sedimentares", "Rochas Magmáticas", "No Sol", "No lava"], correctAnswer: 0, explanation: "Os sedimentos cobrem os restos sem destruí-los pelo calor.", bnccCode: "EF06CI12" },
    { text: "O mármore é um exemplo de rocha:", type: QuestionType.MULTIPLE_CHOICE, options: ["Metamórfica", "Magmática", "Sedimentar", "Líquida"], correctAnswer: 0, explanation: "Vem da transformação do calcário.", bnccCode: "EF06CI12" },
    { text: "O basalto (visto em vulcões) é uma rocha:", type: QuestionType.MULTIPLE_CHOICE, options: ["Magmática", "Sedimentar", "Metamórfica", "Artificial"], correctAnswer: 0, explanation: "Formado pelo resfriamento rápido da lava na superfície.", bnccCode: "EF06CI12" },
    { text: "O arenito é uma rocha formada por grãos de areia:", type: QuestionType.MULTIPLE_CHOICE, options: ["Sedimentar", "Metamórfica", "Magmática", "Voadora"], correctAnswer: 0, explanation: "É a compactação de sedimentos de areia.", bnccCode: "EF06CI12" },
    { text: "O ciclo das rochas mostra que:", type: QuestionType.MULTIPLE_CHOICE, options: ["Uma rocha pode virar outra com o tempo", "Rochas nunca mudam", "Rochas são seres vivos", "Rochas vêm do espaço"], correctAnswer: 0, explanation: "Pressão, calor e erosão transformam os tipos de rocha.", bnccCode: "EF06CI12" },
    { text: "Minerais são:", type: QuestionType.MULTIPLE_CHOICE, options: ["Substâncias sólidas que formam as rochas", "Tipos de plantas", "Animais minúsculos", "Gases coloridos"], correctAnswer: 0, explanation: "As rochas são aglomerados de minerais.", bnccCode: "EF06CI12" }
  ],
  'EF06CI13': [
    { text: "Qual a forma aproximada da Terra?", type: QuestionType.MULTIPLE_CHOICE, options: ["Esférica (Geoide)", "Plana", "Quadrada", "Triangular"], correctAnswer: 0, explanation: "A Terra é arredondada, com leve achatamento nos polos.", bnccCode: "EF06CI13" },
    { text: "Uma evidência da esfericidade da Terra observada no mar é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ver o mastro do navio sumir por último", "A água ser azul", "O som das ondas", "Peixes"], correctAnswer: 0, explanation: "O navio desaparece de baixo para cima devido à curvatura.", bnccCode: "EF06CI13" },
    { text: "As fotos tiradas do espaço mostram que a Terra:", type: QuestionType.MULTIPLE_CHOICE, options: ["É azul e redonda", "É um disco plano", "É um cubo", "Não tem forma"], correctAnswer: 0, explanation: "Satélites