
import { Question, QuestionType } from '../types';

export const GRADE_8_BANK: Record<string, Omit<Question, 'id'>[]> = {
  'EF08CI01': [
    { text: "Qual destas é considerada uma fonte de energia renovável?", type: QuestionType.MULTIPLE_CHOICE, options: ["Energia Solar", "Petróleo", "Carvão Mineral", "Gás Natural"], correctAnswer: 0, explanation: "Fontes renováveis são aquelas que se regeneram naturalmente em curto prazo.", bnccCode: "EF08CI01" },
    { text: "O petróleo é uma fonte de energia do tipo:", type: QuestionType.MULTIPLE_CHOICE, options: ["Não renovável", "Inesgotável", "Limpa", "Renovável"], correctAnswer: 0, explanation: "O petróleo leva milhões de anos para se formar e suas reservas são limitadas.", bnccCode: "EF08CI01" },
    { text: "Qual fonte de energia utiliza o calor interno da Terra?", type: QuestionType.MULTIPLE_CHOICE, options: ["Geotérmica", "Eólica", "Hidrelétrica", "Biomassa"], correctAnswer: 0, explanation: "A energia geotérmica aproveita o calor do interior do planeta.", bnccCode: "EF08CI01" },
    { text: "As usinas hidrelétricas produzem energia a partir de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Movimento da água", "Queima de lixo", "Vento forte", "Luz do Sol"], correctAnswer: 0, explanation: "A força da água em movimento gira as turbinas para gerar eletricidade.", bnccCode: "EF08CI01" },
    { text: "A energia eólica é gerada através de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ventos", "Ondas do mar", "Calor do sol", "Madeira queimada"], correctAnswer: 0, explanation: "Aerogeradores captam a energia cinética dos ventos.", bnccCode: "EF08CI01" },
    { text: "Qual o principal impacto negativo do uso de combustíveis fósseis?", type: QuestionType.MULTIPLE_CHOICE, options: ["Emissão de gases poluentes", "Produção de oxigênio", "Limpeza dos oceanos", "Refrescamento do clima"], correctAnswer: 0, explanation: "A queima de fósseis libera CO2, agravando o efeito estufa.", bnccCode: "EF08CI01" },
    { text: "O bagaço da cana-de-açúcar usado para gerar energia é um exemplo de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Biomassa", "Energia Nuclear", "Energia Fóssil", "Energia Eólica"], correctAnswer: 0, explanation: "Biomassa é matéria orgânica usada como fonte de energia.", bnccCode: "EF08CI01" },
    { text: "Qual destas fontes é mais dependente das condições climáticas diárias?", type: QuestionType.MULTIPLE_CHOICE, options: ["Energia Solar", "Energia Nuclear", "Carvão", "Gás Natural"], correctAnswer: 0, explanation: "A produção solar depende diretamente da presença de sol e ausência de nuvens densas.", bnccCode: "EF08CI01" },
    { text: "A principal vantagem das energias limpas é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Reduzir a poluição ambiental", "Ser mais cara que o petróleo", "Acabar com as florestas", "Aumentar o lixo"], correctAnswer: 0, explanation: "Energias limpas causam baixo ou nenhum impacto ambiental negativo.", bnccCode: "EF08CI01" },
    { text: "O que define uma fonte 'não renovável'?", type: QuestionType.MULTIPLE_CHOICE, options: ["Suas reservas podem acabar", "Ela nunca termina", "Vem do vento", "É produzida pelas plantas"], correctAnswer: 0, explanation: "Fontes não renováveis possuem estoque finito na natureza.", bnccCode: "EF08CI01" }
  ],
  'EF08CI02': [
    { text: "O que é necessário para que uma lâmpada acenda em um circuito?", type: QuestionType.MULTIPLE_CHOICE, options: ["O circuito deve estar fechado", "O circuito deve estar aberto", "Não precisa de fios", "Basta a lâmpada existir"], correctAnswer: 0, explanation: "Um circuito fechado permite a passagem contínua da corrente elétrica.", bnccCode: "EF08CI02" },
    { text: "Qual componente fornece energia para o circuito?", type: QuestionType.MULTIPLE_CHOICE, options: ["Gerador (Pilha/Bateria)", "Interruptor", "Fio condutor", "Lâmpada"], correctAnswer: 0, explanation: "O gerador transforma outras formas de energia em energia elétrica.", bnccCode: "EF08CI02" },
    { text: "Materiais que permitem a passagem fácil da eletricidade são chamados de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Condutores", "Isolantes", "Plásticos", "Borrachas"], correctAnswer: 0, explanation: "Metais como o cobre são excelentes condutores elétricos.", bnccCode: "EF08CI02" },
    { text: "Qual destes é um exemplo de material isolante?", type: QuestionType.MULTIPLE_CHOICE, options: ["Borracha", "Cobre", "Alumínio", "Ferro"], correctAnswer: 0, explanation: "Isolantes dificultam ou impedem a passagem da corrente.", bnccCode: "EF08CI02" },
    { text: "O interruptor em uma casa serve para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Abrir ou fechar o circuito", "Aumentar a voltagem", "Economizar água", "Medir a temperatura"], correctAnswer: 0, explanation: "Ele controla manualmente a passagem da corrente.", bnccCode: "EF08CI02" },
    { text: "Em um circuito em série, se uma lâmpada queima:", type: QuestionType.MULTIPLE_CHOICE, options: ["Todas as outras apagam", "As outras brilham mais", "Nada acontece", "A bateria explode"], correctAnswer: 0, explanation: "No circuito em série há apenas um caminho; se ele for interrompido, tudo para.", bnccCode: "EF08CI02" },
    { text: "Em um circuito em paralelo (como nas casas):", type: QuestionType.MULTIPLE_CHOICE, options: ["As lâmpadas funcionam sozinhas", "Se uma apaga, todas apagam", "Só pode ter uma tomada", "A energia é mais fraca"], correctAnswer: 0, explanation: "Circuitos paralelos oferecem múltiplos caminhos para a corrente.", bnccCode: "EF08CI02" },
    { text: "Qual a unidade de medida da tensão elétrica?", type: QuestionType.MULTIPLE_CHOICE, options: ["Volts (V)", "Amperes (A)", "Watts (W)", "Quilos (kg)"], correctAnswer: 0, explanation: "Volts medem a diferença de potencial elétrico.", bnccCode: "EF08CI02" },
    { text: "O que mede a intensidade da corrente elétrica?", type: QuestionType.MULTIPLE_CHOICE, options: ["Amperes (A)", "Volts (V)", "Metros (m)", "Litros (L)"], correctAnswer: 0, explanation: "Amperes indicam a quantidade de carga que passa por segundo.", bnccCode: "EF08CI02" },
    { text: "Um curto-circuito acontece quando:", type: QuestionType.MULTIPLE_CHOICE, options: ["A corrente passa sem resistência", "A bateria acaba", "O fio é muito longo", "A luz apaga sozinha"], correctAnswer: 0, explanation: "O curto-circuito gera calor excessivo e pode causar incêndios.", bnccCode: "EF08CI02" }
  ],
  'EF08CI07': [
    { text: "Qual a principal característica da reprodução assexuada?", type: QuestionType.MULTIPLE_CHOICE, options: ["Apenas um progenitor participa", "Envolve dois gametas", "Gera descendentes diferentes", "É exclusiva de animais grandes"], correctAnswer: 0, explanation: "Na assexuada, um único ser gera descendentes geneticamente iguais.", bnccCode: "EF08CI07" },
    { text: "A reprodução sexuada garante:", type: QuestionType.MULTIPLE_CHOICE, options: ["Variabilidade genética", "Clones perfeitos", "Rapidez extrema", "Menor gasto de energia"], correctAnswer: 0, explanation: "A mistura de genes de dois pais gera indivíduos únicos.", bnccCode: "EF08CI07" },
    { text: "Como se chamam as células sexuais?", type: QuestionType.MULTIPLE_CHOICE, options: ["Gametas", "Neurônios", "Hemácias", "Tecidos"], correctAnswer: 0, explanation: "Espermatozoides e óvulos são exemplos de gametas.", bnccCode: "EF08CI07" },
    { text: "A união do espermatozoide com o óvulo chama-se:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fecundação", "Brotamento", "Fragmentação", "Clonagem"], correctAnswer: 0, explanation: "Dessa união surge o zigoto.", bnccCode: "EF08CI07" },
    { text: "As bactérias se reproduzem principalmente por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Divisão binária", "Parto", "Ovos", "Sementes"], correctAnswer: 0, explanation: "Uma célula se divide em duas iguais (assexuada).", bnccCode: "EF08CI07" },
    { text: "Um exemplo de reprodução assexuada em plantas é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Estaquia (plantar um galho)", "Polinização", "Frutos com sementes", "Vento"], correctAnswer: 0, explanation: "A estaquia gera uma nova planta idêntica à original.", bnccCode: "EF08CI07" },
    { text: "Vantagem da reprodução assexuada:", type: QuestionType.MULTIPLE_CHOICE, options: ["Rápida colonização de ambientes", "Adaptação a mudanças bruscas", "Gera seres mais inteligentes", "Mistura de DNA"], correctAnswer: 0, explanation: "Permite aumentar a população em pouco tempo se as condições forem boas.", bnccCode: "EF08CI07" },
    { text: "O brotamento é comum em quais seres?", type: QuestionType.MULTIPLE_CHOICE, options: ["Hidras e leveduras", "Mamíferos", "Aves", "Répteis"], correctAnswer: 0, explanation: "Um pequeno 'broto' cresce no corpo do pai e se desprende.", bnccCode: "EF08CI07" },
    { text: "Qual destas requer mais tempo e energia para ocorrer?", type: QuestionType.MULTIPLE_CHOICE, options: ["Reprodução Sexuada", "Divisão de bactérias", "Brotamento", "Cisão"], correctAnswer: 0, explanation: "Envolve busca por parceiro, rituais e gestação.", bnccCode: "EF08CI07" },
    { text: "Na reprodução sexuada, o novo ser recebe:", type: QuestionType.MULTIPLE_CHOICE, options: ["Metade do DNA de cada pai", "Todo o DNA da mãe apenas", "Nenhum DNA", "O DNA do pai apenas"], correctAnswer: 0, explanation: "Cada gameta traz metade da informação genética.", bnccCode: "EF08CI07" }
  ],
  'EF08CI12': [
    { text: "O que causa um eclipse solar?", type: QuestionType.MULTIPLE_CHOICE, options: ["A Lua fica entre a Terra e o Sol", "A Terra fica entre a Lua e o Sol", "O Sol fica entre a Lua e a Terra", "As nuvens cobrem o Sol"], correctAnswer: 0, explanation: "A sombra da Lua é projetada sobre uma parte da Terra.", bnccCode: "EF08CI12" },
    { text: "Em qual fase da Lua ocorre o eclipse solar?", type: QuestionType.MULTIPLE_CHOICE, options: ["Lua Nova", "Lua Cheia", "Lua Crescente", "Lua Minguante"], correctAnswer: 0, explanation: "No eclipse solar, a face iluminada da Lua está voltada para o Sol.", bnccCode: "EF08CI12" },
    { text: "O que causa um eclipse lunar?", type: QuestionType.MULTIPLE_CHOICE, options: ["A Terra fica entre o Sol e a Lua", "A Lua fica entre o Sol e a Terra", "O Sol se apaga", "A Lua entra em um vulcão"], correctAnswer: 0, explanation: "A Terra projeta sua sombra sobre a superfície da Lua.", bnccCode: "EF08CI12" },
    { text: "Em qual fase da Lua ocorre o eclipse lunar?", type: QuestionType.MULTIPLE_CHOICE, options: ["Lua Cheia", "Lua Nova", "Lua Quarto Minguante", "Lua Quarto Crescente"], correctAnswer: 0, explanation: "A Lua deve estar oposta ao Sol em relação à Terra.", bnccCode: "EF08CI12" },
    { text: "A região de sombra total durante um eclipse é chamada de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Umbra", "Penumbra", "Aura", "Reflexo"], correctAnswer: 0, explanation: "A umbra é a parte mais escura da sombra.", bnccCode: "EF08CI12" },
    { text: "A região de sombra parcial é a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Penumbra", "Umbra", "Centro", "Escuridão"], correctAnswer: 0, explanation: "Nesta área, o eclipse é visto como parcial.", bnccCode: "EF08CI12" },
    { text: "Por que não temos eclipses todos os meses?", type: QuestionType.MULTIPLE_CHOICE, options: ["A órbita da Lua é inclinada", "A Lua gira muito rápido", "O Sol se move demais", "A Terra é plana"], correctAnswer: 0, explanation: "Os planos das órbitas da Terra e da Lua não são perfeitamente alinhados.", bnccCode: "EF08CI12" },
    { text: "Qual eclipse pode ser visto com segurança a olho nu?", type: QuestionType.MULTIPLE_CHOICE, options: ["Eclipse Lunar", "Eclipse Solar", "Nenhum", "Ambos"], correctAnswer: 0, explanation: "Olhar diretamente para o Sol (mesmo em eclipse) danifica os olhos; a Lua é segura.", bnccCode: "EF08CI12" },
    { text: "O fenômeno conhecido como 'Lua de Sangue' é um:", type: QuestionType.MULTIPLE_CHOICE, options: ["Eclipse Lunar Total", "Eclipse Solar Total", "Nascer da Lua", "Fase da Lua Nova"], correctAnswer: 0, explanation: "A atmosfera da Terra desvia luz vermelha para a Lua durante o eclipse.", bnccCode: "EF08CI12" },
    { text: "Durante um eclipse solar total, o que se torna visível ao redor do Sol?", type: QuestionType.MULTIPLE_CHOICE, options: ["A Coroa Solar", "O Núcleo do Sol", "Outras galáxias", "A Lua vira fogo"], correctAnswer: 0, explanation: "A coroa é a atmosfera externa do Sol, normalmente invisível pelo brilho.", bnccCode: "EF08CI12" }
  ],
  'EF08CI17CE': [
    { text: "Qual a importância da vacinação coletiva?", type: QuestionType.MULTIPLE_CHOICE, options: ["Protege quem vacinou e quem não pode vacinar", "Serve apenas para o indivíduo", "Não tem efeito na sociedade", "Aumenta a sujeira"], correctAnswer: 0, explanation: "Cria a 'imunidade de rebanho', bloqueando a circulação do vírus.", bnccCode: "EF08CI17CE" },
    { text: "Saúde coletiva envolve principalmente:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ações do governo e da comunidade", "Apenas ir ao médico sozinho", "Comprar remédios caros", "Ficar em casa"], correctAnswer: 0, explanation: "Trata-se de políticas públicas como saneamento e campanhas.", bnccCode: "EF08CI17CE" },
    { text: "O saneamento básico é fundamental para prevenir:", type: QuestionType.MULTIPLE_CHOICE, options: ["Doenças infectocontagiosas", "Cansaço físico", "Fome", "Quebra de ossos"], correctAnswer: 0, explanation: "Água limpa e esgoto tratado evitam cólera, verminoses, etc.", bnccCode: "EF08CI17CE" },
    { text: "O sistema público de saúde do Brasil é o:", type: QuestionType.MULTIPLE_CHOICE, options: ["SUS", "INSS", "ONU", "NASA"], correctAnswer: 0, explanation: "O Sistema Único de Saúde é gratuito e universal.", bnccCode: "EF08CI17CE" },
    { text: "Uma medida de saúde individual que ajuda a coletividade:", type: QuestionType.MULTIPLE_CHOICE, options: ["Lavar as mãos e usar máscara", "Dormir 12 horas", "Comer chocolate", "Comprar sapatos novos"], correctAnswer: 0, explanation: "Higiene pessoal evita a transmissão de germes para outros.", bnccCode: "EF08CI17CE" },
    { text: "A dengue é um problema de saúde coletiva porque:", type: QuestionType.MULTIPLE_CHOICE, options: ["O mosquito circula por toda a vizinhança", "Apenas uma pessoa fica doente", "O mosquito vive no gelo", "Não tem cura"], correctAnswer: 0, explanation: "O controle do mosquito depende da limpeza de todas as casas.", bnccCode: "EF08CI17CE" },
    { text: "O descarte correto do lixo evita:", type: QuestionType.MULTIPLE_CHOICE, options: ["Proliferação de ratos e insetos", "O frio", "O sol forte", "O nascimento de árvores"], correctAnswer: 0, explanation: "Lixo acumulado atrai vetores de doenças.", bnccCode: "EF08CI17CE" },
    { text: "Exemplo de doença erradicada no Brasil via vacinação:", type: QuestionType.MULTIPLE_CHOICE, options: ["Poliomielite (Paralisia Infantil)", "Gripe Comum", "Dor de cabeça", "Diabetes"], correctAnswer: 0, explanation: "Graças às campanhas com o 'Zé Gotinha'.", bnccCode: "EF08CI17CE" },
    { text: "Beber água filtrada ou fervida previne:", type: QuestionType.MULTIPLE_CHOICE, options: ["Diarreia e verminoses", "Miopia", "Resfriado", "Surdez"], correctAnswer: 0, explanation: "Elimina microrganismos causadores de doenças intestinais.", bnccCode: "EF08CI17CE" },
    { text: "A vigilância sanitária serve para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fiscalizar a higiene de alimentos e serviços", "Vender comida", "Dormir nas lojas", "Limpar as ruas"], correctAnswer: 0, explanation: "Garante que o que consumimos não nos fará mal.", bnccCode: "EF08CI17CE" }
  ]
};
