
import { Question, QuestionType } from '../types';

export const GRADE_9_BANK: Record<string, Omit<Question, 'id'>[]> = {
  'EF09CI01': [
    { text: "A passagem da água do estado sólido (gelo) para o líquido chama-se:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fusão", "Solidificação", "Sublimação", "Ebulição"], correctAnswer: 0, explanation: "Fusão é o processo de derretimento pelo aumento de temperatura.", bnccCode: "EF09CI01" },
    { text: "O que ocorre na sublimação?", type: QuestionType.MULTIPLE_CHOICE, options: ["Sólido vai para o gasoso diretamente", "Líquido vira gelo", "Gás vira líquido", "Sólido vira líquido"], correctAnswer: 0, explanation: "A naftalina e o gelo seco são exemplos comuns de sublimação.", bnccCode: "EF09CI01" },
    { text: "A formação de gotículas de água do lado de fora de um copo gelado é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Condensação", "Vaporização", "Ebulição", "Fusão"], correctAnswer: 0, explanation: "O vapor de água no ar esfria ao tocar o copo e vira líquido.", bnccCode: "EF09CI01" },
    { text: "A ebulição é um tipo de vaporização que ocorre de forma:", type: QuestionType.MULTIPLE_CHOICE, options: ["Rápida e com bolhas", "Lenta e silenciosa", "Natural e fria", "Apenas no vácuo"], correctAnswer: 0, explanation: "Diferente da evaporação, a ebulição é turbulenta e rápida.", bnccCode: "EF09CI01" },
    { text: "Para o gelo derreter, ele precisa:", type: QuestionType.MULTIPLE_CHOICE, options: ["Ganhar calor", "Perder calor", "Ficar no escuro", "Ser apertado"], correctAnswer: 0, explanation: "A energia térmica aumenta a agitação das moléculas.", bnccCode: "EF09CI01" },
    { text: "O estado físico onde as moléculas estão mais afastadas e agitadas é o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Gasoso", "Líquido", "Sólido", "Cristalino"], correctAnswer: 0, explanation: "Gases não têm forma nem volume definidos.", bnccCode: "EF09CI01" },
    { text: "A solidificação é o processo inverso da:", type: QuestionType.MULTIPLE_CHOICE, options: ["Fusão", "Ebulição", "Sublimação", "Condensação"], correctAnswer: 0, explanation: "Solidificação é o congelamento (Líquido -> Sólido).", bnccCode: "EF09CI01" },
    { text: "O ponto de ebulição da água pura ao nível do mar é:", type: QuestionType.MULTIPLE_CHOICE, options: ["100°C", "0°C", "50°C", "200°C"], correctAnswer: 0, explanation: "É a temperatura padrão onde a água vira vapor.", bnccCode: "EF09CI01" },
    { text: "Na vaporização, a matéria passa do estado:", type: QuestionType.MULTIPLE_CHOICE, options: ["Líquido para o gasoso", "Sólido para o gasoso", "Gás para líquido", "Líquido para sólido"], correctAnswer: 0, explanation: "Pode ocorrer por evaporação, ebulição ou calefação.", bnccCode: "EF09CI01" },
    { text: "O estado sólido possui:", type: QuestionType.MULTIPLE_CHOICE, options: ["Forma e volume definidos", "Apenas volume definido", "Apenas forma definida", "Nenhuma definição"], correctAnswer: 0, explanation: "As partículas estão bem organizadas e próximas.", bnccCode: "EF09CI01" }
  ],
  'EF09CI03': [
    { text: "Qual partícula atômica possui carga positiva?", type: QuestionType.MULTIPLE_CHOICE, options: ["Próton", "Elétron", "Nêutron", "Fóton"], correctAnswer: 0, explanation: "Os prótons ficam no núcleo da célula.", bnccCode: "EF09CI03" },
    { text: "Os elétrons ficam localizados na:", type: QuestionType.MULTIPLE_CHOICE, options: ["Eletrosfera", "Núcleo", "Litosfera", "Biosfera"], correctAnswer: 0, explanation: "Eles giram ao redor do núcleo.", bnccCode: "EF09CI03" },
    { text: "O átomo é formado basicamente por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Núcleo e Eletrosfera", "Apenas água", "Apenas eletricidade", "Células"], correctAnswer: 0, explanation: "É a estrutura básica da matéria.", bnccCode: "EF09CI03" },
    { text: "Qual partícula não possui carga elétrica?", type: QuestionType.MULTIPLE_CHOICE, options: ["Nêutron", "Próton", "Elétron", "Íon"], correctAnswer: 0, explanation: "Os nêutrons ajudam a estabilizar o núcleo.", bnccCode: "EF09CI03" },
    { text: "O primeiro modelo atômico (bola de bilhar) foi proposto por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Dalton", "Thomson", "Rutherford", "Bohr"], correctAnswer: 0, explanation: "Dalton via o átomo como uma esfera maciça e indivisível.", bnccCode: "EF09CI03" },
    { text: "O modelo de 'pudim de passas' foi criado por:", type: QuestionType.MULTIPLE_CHOICE, options: ["Thomson", "Dalton", "Bohr", "Chadwick"], correctAnswer: 0, explanation: "Ele descobriu os elétrons mergulhados em uma massa positiva.", bnccCode: "EF09CI03" },
    { text: "Rutherford descobriu que o átomo possui um grande:", type: QuestionType.MULTIPLE_CHOICE, options: ["Espaço vazio", "Núcleo de gelo", "Anel de fogo", "Manto líquido"], correctAnswer: 0, explanation: "A maior parte do átomo é vácuo.", bnccCode: "EF09CI03" },
    { text: "A soma de prótons e nêutrons define a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Massa atômica", "Carga elétrica", "Cor do átomo", "Velocidade"], correctAnswer: 0, explanation: "Quase toda a massa do átomo está no núcleo.", bnccCode: "EF09CI03" },
    { text: "O número atômico (Z) representa a quantidade de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Prótons", "Elétrons", "Nêutrons", "Moléculas"], correctAnswer: 0, explanation: "Identifica o elemento químico na tabela periódica.", bnccCode: "EF09CI03" },
    { text: "Um átomo neutro possui:", type: QuestionType.MULTIPLE_CHOICE, options: ["Mesma quantidade de prótons e elétrons", "Mais prótons", "Mais elétrons", "Apenas nêutrons"], correctAnswer: 0, explanation: "As cargas positivas e negativas se anulam.", bnccCode: "EF09CI03" }
  ],
  'EF09CI09': [
    { text: "Quem é considerado o 'Pai da Genética'?", type: QuestionType.MULTIPLE_CHOICE, options: ["Gregor Mendel", "Charles Darwin", "Albert Einstein", "Louis Pasteur"], correctAnswer: 0, explanation: "Mendel estudou a hereditariedade usando ervilhas.", bnccCode: "EF09CI09" },
    { text: "Onde fica guardada a nossa informação genética?", type: QuestionType.MULTIPLE_CHOICE, options: ["No DNA", "No sangue apenas", "No estômago", "Nos músculos"], correctAnswer: 0, explanation: "O DNA contém as instruções para construir e manter o organismo.", bnccCode: "EF09CI09" },
    { text: "Um gene dominante é representado por letras:", type: QuestionType.MULTIPLE_CHOICE, options: ["Maiúsculas (AA, Aa)", "Minúsculas (aa)", "Números", "Símbolos"], correctAnswer: 0, explanation: "Ele se expressa mesmo em dose simples.", bnccCode: "EF09CI09" },
    { text: "Para uma característica recessiva aparecer, o indivíduo deve ser:", type: QuestionType.MULTIPLE_CHOICE, options: ["Homozigoto recessivo (aa)", "Heterozigoto (Aa)", "Grande", "Forte"], correctAnswer: 0, explanation: "Precisa de dois genes 'escondidos' para se manifestar.", bnccCode: "EF09CI09" },
    { text: "Genótipo refere-se ao:", type: QuestionType.MULTIPLE_CHOICE, options: ["Conjunto de genes (DNA)", "Aparência física", "Nome da pessoa", "Local onde mora"], correctAnswer: 0, explanation: "É a constituição genética oculta.", bnccCode: "EF09CI09" },
    { text: "Fenótipo é a união do genótipo com o:", type: QuestionType.MULTIPLE_CHOICE, options: ["Meio ambiente", "Sobrenome", "Alimento", "Sono"], correctAnswer: 0, explanation: "É o que vemos: cor dos olhos, altura, etc.", bnccCode: "EF09CI09" },
    { text: "Cada característica é determinada por um par de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Alelos", "Órgãos", "Células", "Ossos"], correctAnswer: 0, explanation: "Recebemos um alelo de cada progenitor.", bnccCode: "EF09CI09" },
    { text: "O cruzamento de Aa com aa resulta em quais chances de Aa?", type: QuestionType.MULTIPLE_CHOICE, options: ["50%", "100%", "25%", "0%"], correctAnswer: 0, explanation: "Metade será Aa e metade aa.", bnccCode: "EF09CI09" },
    { text: "A cor dos olhos é uma característica:", type: QuestionType.MULTIPLE_CHOICE, options: ["Hereditária", "Adquirida por hábito", "Inexistente", "De sorte"], correctAnswer: 0, explanation: "Passada de pais para filhos via DNA.", bnccCode: "EF09CI09" },
    { text: "A primeira lei de Mendel é conhecida como lei da:", type: QuestionType.MULTIPLE_CHOICE, options: ["Segregação dos Fatores", "Evolução", "Gravidade", "Inércia"], correctAnswer: 0, explanation: "Os alelos se separam na formação dos gametas.", bnccCode: "EF09CI09" }
  ],
  'EF09CI18CE': [
    { text: "A 1ª Lei de Newton também é chamada de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Lei da Inércia", "Lei da Ação e Reação", "Lei da Gravidade", "Lei da Energia"], correctAnswer: 0, explanation: "Diz que um corpo tende a manter seu estado de repouso ou movimento.", bnccCode: "EF09CI18CE" },
    { text: "Segundo a inércia, um objeto parado tende a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Continuar parado", "Sair correndo", "Explodir", "Diminuir de tamanho"], correctAnswer: 0, explanation: "A menos que uma força externa atue sobre ele.", bnccCode: "EF09CI18CE" },
    { text: "Por que usamos cinto de segurança?", type: QuestionType.MULTIPLE_CHOICE, options: ["Por causa da inércia (nos impede de voar para frente)", "Para enfeitar o carro", "Para o carro andar mais rápido", "Não tem utilidade"], correctAnswer: 0, explanation: "Nosso corpo tende a continuar em movimento se o carro frear.", bnccCode: "EF09CI18CE" },
    { text: "A força que puxa os objetos para o centro da Terra é a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Gravidade", "Inércia", "Atrito", "Elétrica"], correctAnswer: 0, explanation: "Formulada por Isaac Newton após observar a queda dos corpos.", bnccCode: "EF09CI18CE" },
    { text: "Quanto maior a massa de um objeto, maior será sua:", type: QuestionType.MULTIPLE_CHOICE, options: ["Inércia", "Velocidade", "Cor", "Temperatura"], correctAnswer: 0, explanation: "Massa é a medida da inércia: mais difícil de mover ou parar.", bnccCode: "EF09CI18CE" },
    { text: "A força peso depende da massa e da:", type: QuestionType.MULTIPLE_CHOICE, options: ["Gravidade", "Luz", "Forma", "Idade"], correctAnswer: 0, explanation: "Peso = Massa x Gravidade.", bnccCode: "EF09CI18CE" },
    { text: "Se você estiver no espaço, longe de planetas, sua massa:", type: QuestionType.MULTIPLE_CHOICE, options: ["Continua a mesma", "Vira zero", "Aumenta muito", "Diminui"], correctAnswer: 0, explanation: "Massa é a quantidade de matéria; o peso é que muda.", bnccCode: "EF09CI18CE" },
    { text: "Quem formulou as leis do movimento?", type: QuestionType.MULTIPLE_CHOICE, options: ["Isaac Newton", "Galileu Galilei", "Marie Curie", "Nikola Tesla"], correctAnswer: 0, explanation: "Suas leis são a base da física clássica.", bnccCode: "EF09CI18CE" },
    { text: "Um corpo em movimento retilíneo uniforme tende a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Manter sua velocidade e direção", "Parar sozinho", "Fazer curvas", "Aumentar a velocidade"], correctAnswer: 0, explanation: "Sem forças externas, o movimento é perpétuo.", bnccCode: "EF09CI18CE" },
    { text: "A resistência que um objeto oferece para mudar de estado é a:", type: QuestionType.MULTIPLE_CHOICE, options: ["Inércia", "Fricção", "Energia", "Massa"], correctAnswer: 0, explanation: "É a propriedade básica da matéria descrita por Newton.", bnccCode: "EF09CI18CE" }
  ],
  'EF09CI19CE': [
    { text: "O que é Biotecnologia?", type: QuestionType.MULTIPLE_CHOICE, options: ["Uso de seres vivos para criar produtos", "Estudo apenas de robôs", "Fabricação de carros", "Culinária comum"], correctAnswer: 0, explanation: "Utiliza organismos, células ou moléculas para fins práticos.", bnccCode: "EF09CI19CE" },
    { text: "Um exemplo antigo de biotecnologia é a fabricação de:", type: QuestionType.MULTIPLE_CHOICE, options: ["Pão e Iogurte", "Plástico", "Computadores", "Vidro"], correctAnswer: 0, explanation: "Usa leveduras e bactérias há milhares de anos.", bnccCode: "EF09CI19CE" },
    { text: "O que são alimentos transgênicos?", type: QuestionType.MULTIPLE_CHOICE, options: ["Modificados geneticamente em laboratório", "Alimentos que vêm de outros planetas", "Comidas coloridas artificialmente", "Alimentos estragados"], correctAnswer: 0, explanation: "Possuem genes de outras espécies para melhorar resistência ou nutrição.", bnccCode: "EF09CI19CE" },
    { text: "A clonagem produz indivíduos:", type: QuestionType.MULTIPLE_CHOICE, options: ["Geneticamente idênticos", "Completamente diferentes", "Apenas robôs", "Mais inteligentes"], correctAnswer: 0, explanation: "É a criação de uma cópia genética exata.", bnccCode: "EF09CI19CE" },
    { text: "A insulina produzida por bactérias é um avanço da:", type: QuestionType.MULTIPLE_CHOICE, options: ["Engenharia Genética", "Mecânica", "Astronomia", "Geologia"], correctAnswer: 0, explanation: "Bactérias recebem o gene humano para fabricar o remédio.", bnccCode: "EF09CI19CE" },
    { text: "Células-tronco são importantes porque podem:", type: QuestionType.MULTIPLE_CHOICE, options: ["Se transformar em qualquer tipo de célula", "Explodir vírus", "Limpar o sangue", "Produzir luz"], correctAnswer: 0, explanation: "Têm grande potencial para tratar doenças e regenerar tecidos.", bnccCode: "EF09CI19CE" },
    { text: "O uso de bactérias para limpar derramamentos de óleo é:", type: QuestionType.MULTIPLE_CHOICE, options: ["Biorremediação", "Clonagem", "Vacinação", "Evolução"], correctAnswer: 0, explanation: "Uso de seres vivos para remover poluentes.", bnccCode: "EF09CI19CE" },
    { text: "A vacina de RNA é um exemplo de biotecnologia aplicada à:", type: QuestionType.MULTIPLE_CHOICE, options: ["Saúde", "Agricultura", "Indústria têxtil", "Construção civil"], correctAnswer: 0, explanation: "Usa tecnologia genética para ensinar o corpo a se defender.", bnccCode: "EF09CI19CE" },
    { text: "O teste de DNA serve para:", type: QuestionType.MULTIPLE_CHOICE, options: ["Identificar parentesco ou crimes", "Saber se a pessoa está com fome", "Medir a altura", "Ver a cor dos olhos"], correctAnswer: 0, explanation: "Analisa padrões únicos no código genético.", bnccCode: "EF09CI19CE" },
    { text: "Biotecnologia na agricultura ajuda a criar plantas:", type: QuestionType.MULTIPLE_CHOICE, options: ["Mais resistentes a pragas", "Que não precisam de água", "Que falam", "Azuis"], correctAnswer: 0, explanation: "Reduz o uso de agrotóxicos químicos.", bnccCode: "EF09CI19CE" }
  ]
};
